Wed Apr 16 01:55:04 EDT 2025
Running on node: spdr18
no change     /usr/local/sw/anaconda/anaconda3/condabin/conda
no change     /usr/local/sw/anaconda/anaconda3/bin/conda
no change     /usr/local/sw/anaconda/anaconda3/bin/conda-env
no change     /usr/local/sw/anaconda/anaconda3/bin/activate
no change     /usr/local/sw/anaconda/anaconda3/bin/deactivate
no change     /usr/local/sw/anaconda/anaconda3/etc/profile.d/conda.sh
no change     /usr/local/sw/anaconda/anaconda3/etc/fish/conf.d/conda.fish
no change     /usr/local/sw/anaconda/anaconda3/shell/condabin/Conda.psm1
no change     /usr/local/sw/anaconda/anaconda3/shell/condabin/conda-hook.ps1
no change     /usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /usr/local/sw/anaconda/anaconda3/etc/profile.d/conda.csh
no change     /home/km3nc/.bashrc
No action taken.
Starting distillation training...
/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
W0416 01:55:07.189502 3722660 site-packages/torch/distributed/run.py:792] 
W0416 01:55:07.189502 3722660 site-packages/torch/distributed/run.py:792] *****************************************
W0416 01:55:07.189502 3722660 site-packages/torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0416 01:55:07.189502 3722660 site-packages/torch/distributed/run.py:792] *****************************************
/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(
2025-04-16 01:55:12.029925: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-16 01:55:12.029923: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-16 01:55:12.066165: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-04-16 01:55:12.066199: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-04-16 01:55:12.066414: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-04-16 01:55:12.066437: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-04-16 01:55:12.067215: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-16 01:55:12.067427: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-16 01:55:12.072671: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-16 01:55:12.072863: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-16 01:55:12.999321: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2025-04-16 01:55:12.999390: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/km3nc/babylm/distill-ensemble-pretraining-baby-llama.py", line 42, in <module>
  File "/home/km3nc/babylm/distill-ensemble-pretraining-baby-llama.py", line 42, in <module>
    tokenizer = GPT2TokenizerFast(tokenizer_file= str(tokenizer_path))
  File "/home/km3nc/.local/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 96, in __init__
    tokenizer = GPT2TokenizerFast(tokenizer_file= str(tokenizer_path))
  File "/home/km3nc/.local/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 96, in __init__
    super().__init__(
  File "/home/km3nc/.local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 117, in __init__
    super().__init__(
  File "/home/km3nc/.local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 117, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)    
fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: ExceptionNo such file or directory (os error 2): 
No such file or directory (os error 2)
W0416 01:55:16.431485 3722660 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3722842 closing signal SIGTERM
E0416 01:55:16.463505 3722660 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3722841) of binary: /usr/local/sw/anaconda/anaconda3/bin/python
Traceback (most recent call last):
  File "/usr/local/sw/anaconda/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/sw/anaconda/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
distill-ensemble-pretraining-baby-llama.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-04-16_01:55:16
  host      : spdr18.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3722841)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Command exited with non-zero status 1
	Command being timed: "torchrun --nproc_per_node=2 distill-ensemble-pretraining-baby-llama.py"
	User time (seconds): 14.58
	System time (seconds): 2.70
	Percent of CPU this job got: 153%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:11.28
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1161528
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 979
	Minor (reclaiming a frame) page faults: 649015
	Voluntary context switches: 60534
	Involuntary context switches: 825575
	Swaps: 0
	File system inputs: 56
	File system outputs: 136
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
